# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'announce_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AnnounceForm(object):
    def setupUi(self, AnnounceForm):
        AnnounceForm.setObjectName("AnnounceForm")
        AnnounceForm.resize(674, 472)
        self.verticalLayout = QtWidgets.QVBoxLayout(AnnounceForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.announcelabel = QtWidgets.QLabel(AnnounceForm)
        self.announcelabel.setObjectName("announcelabel")
        self.verticalLayout.addWidget(self.announcelabel)
        self.line = QtWidgets.QFrame(AnnounceForm)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.anntimelabel = QtWidgets.QLabel(AnnounceForm)
        self.anntimelabel.setObjectName("anntimelabel")
        self.verticalLayout.addWidget(self.anntimelabel)
        self.annline = QtWidgets.QFrame(AnnounceForm)
        self.annline.setFrameShape(QtWidgets.QFrame.HLine)
        self.annline.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.annline.setObjectName("annline")
        self.verticalLayout.addWidget(self.annline)
        self.announcetextEdit = QtWidgets.QTextEdit(AnnounceForm)
        self.announcetextEdit.setObjectName("announcetextEdit")
        self.verticalLayout.addWidget(self.announcetextEdit)

        self.retranslateUi(AnnounceForm)
        QtCore.QMetaObject.connectSlotsByName(AnnounceForm)

    def retranslateUi(self, AnnounceForm):
        _translate = QtCore.QCoreApplication.translate
        AnnounceForm.setWindowTitle(_translate("AnnounceForm", "Form"))
        self.announcelabel.setText(_translate("AnnounceForm", "TextLabel"))
        self.anntimelabel.setText(_translate("AnnounceForm", "TextLabel"))
