# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_home_Form(object):
    def setupUi(self, home_Form):
        home_Form.setObjectName("home_Form")
        home_Form.resize(637, 513)
        self.gridLayout = QtWidgets.QGridLayout(home_Form)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(home_Form)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 613, 489))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(home_Form)
        QtCore.QMetaObject.connectSlotsByName(home_Form)

    def retranslateUi(self, home_Form):
        _translate = QtCore.QCoreApplication.translate
        home_Form.setWindowTitle(_translate("home_Form", "Form"))
