# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'monitor_module.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Monitor_Form(object):
    def setupUi(self, Monitor_Form):
        Monitor_Form.setObjectName("Monitor_Form")
        Monitor_Form.resize(543, 423)
        self.verticalLayoutWidget = QtWidgets.QWidget(Monitor_Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 531, 411))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.monitor_ptn_cancel = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.monitor_ptn_cancel.setObjectName("monitor_ptn_cancel")
        self.horizontalLayout.addWidget(self.monitor_ptn_cancel)
        self.monitor_ptn_save = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.monitor_ptn_save.setObjectName("monitor_ptn_save")
        self.horizontalLayout.addWidget(self.monitor_ptn_save)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Monitor_Form)
        QtCore.QMetaObject.connectSlotsByName(Monitor_Form)

    def retranslateUi(self, Monitor_Form):
        _translate = QtCore.QCoreApplication.translate
        Monitor_Form.setWindowTitle(_translate("Monitor_Form", "Form"))
        self.monitor_ptn_cancel.setText(_translate("Monitor_Form", "Cancel"))
        self.monitor_ptn_save.setText(_translate("Monitor_Form", "Save"))
