# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'update_courselist.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(520, 800)
        Form.setMinimumSize(QtCore.QSize(520, 800))
        Form.setMaximumSize(QtCore.QSize(520, 800))
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 501, 781))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.coursename_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.coursename_label.setObjectName("coursename_label")
        self.verticalLayout.addWidget(self.coursename_label)
        self.coursenum_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.coursenum_label.setObjectName("coursenum_label")
        self.verticalLayout.addWidget(self.coursenum_label)
        self.listWidget = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.coursename_label.setText(_translate("Form", "TextLabel"))
        self.coursenum_label.setText(_translate("Form", "TextLabel"))

